# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: app
    main: ./cmd/app
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

dockers:
  # Build architecture-specific images from the already-built goreleaser binaries.
  - id: app-amd64
    ids: [app]
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}-amd64
    dockerfile: Dockerfile
    use: buildx
  - id: app-arm64
    ids: [app]
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}-arm64
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - name_template: ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}-arm64
  - name_template: ghcr.io/{{ .Env.IMAGE_REPO_LC }}:latest
    image_templates:
      - ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.IMAGE_REPO_LC }}:{{ .Tag }}-arm64
