x-common-config: &common-config
  restart: no

services:
  backend:
    <<: *common-config
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
    user: 1000:1000
