openapi: 3.0.3
info:
  title: DocPort.io API
  description: DocPort.io API documentation
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
paths:
  /api/v1/projects:
    get:
      operationId: listProjects
      summary: Find all projects
      tags:
        - projects
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListProjectsResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'
    post:
      operationId: createProject
      summary: Create a new project
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/InternalServerError'
  /api/v1/projects/{projectId}:
    get:
      operationId: getProjectById
      summary: Get a project by ID
      tags:
        - projects
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    put:
      operationId: updateProjectById
      summary: Update a project by ID
      tags:
        - projects
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      operationId: deleteProjectById
      summary: Delete a project by ID
      tags:
        - projects
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      responses:
        204:
          description: No Content
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    Limit:
      name: limit
      in: query
      description: Maximum of items to return per page
      required: false
      schema:
        type: integer
        format: int64
        example: 100

    Offset:
      name: offset
      in: query
      description: Offset of items to skip
      required: false
      schema:
        type: integer
        format: int64
        example: 0

    ProjectId:
      name: projectId
      in: path
      required: true
      schema:
        type: integer
        format: int64

  responses:
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    ListProjectsResponse:
      type: object
      required:
        - limit
        - offset
        - projects
      properties:
        limit:
          type: integer
          format: int64
        offset:
          type: integer
          format: int64
        projects:
          type: array
          items:
            $ref: '#/components/schemas/ProjectResponse'

    ProjectResponse:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - slug
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        createdAt:
          type: string
          format: date-time
          example: '2026-01-01T00:00:00.000Z'
        updatedAt:
          type: string
          format: date-time
          example: '2026-01-01T00:00:00.000Z'
        slug:
          type: string
          pattern: '^[a-z0-9-_]+$'
          example: my-project
        name:
          type: string
          example: My Project

    CreateProjectRequest:
      type: object
      required:
        - slug
        - name
      properties:
        slug:
          type: string
          pattern: '^[a-z0-9-_]+$'
          example: my-project
        name:
          type: string
          example: My Project

    UpdateProjectRequest:
      type: object
      required:
        - slug
        - name
      properties:
        slug:
          type: string
          pattern: '^[a-z0-9-_]+$'
          example: my-project
        name:
          type: string
          example: My Project
