// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	Name       string
	Size       *int64
	Path       *string
	MimeType   *string
	IsComplete bool
}

type Location struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	Address   *string
	Lat       *float64
	Lon       *float64
}

type Project struct {
	ID         int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	Slug       string
	Name       string
	LocationID *int32
}

type User struct {
	ID                int64
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	Name              string
	Email             string
	EmailVerified     bool
	KeycloakReference *string
}

type Version struct {
	ID          int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Name        string
	Description *string
	ProjectID   int64
}

type VersionsFile struct {
	VersionID int64
	FileID    int64
}
