// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const attachFileToVersion = `-- name: AttachFileToVersion :exec
INSERT INTO versions_files (version_id, file_id)
VALUES ($1, $2)
`

type AttachFileToVersionParams struct {
	VersionID int64
	FileID    int64
}

func (q *Queries) AttachFileToVersion(ctx context.Context, arg *AttachFileToVersionParams) error {
	_, err := q.db.Exec(ctx, attachFileToVersion, arg.VersionID, arg.FileID)
	return err
}

const countFilesByVersionId = `-- name: CountFilesByVersionId :one

SELECT count(files.id)
FROM files
         INNER JOIN versions_files ON files.id = versions_files.file_id
WHERE versions_files.version_id = $1
`

// Files
func (q *Queries) CountFilesByVersionId(ctx context.Context, versionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByVersionId, versionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT count(projects.id)
FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVersionsByProjectId = `-- name: CountVersionsByProjectId :one

SELECT count(versions.id)
FROM versions
WHERE project_id = $1
`

// Versions
func (q *Queries) CountVersionsByProjectId(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countVersionsByProjectId, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (name, size, path, mime_type, is_complete)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, size, path, mime_type, is_complete
`

type CreateFileParams struct {
	Name       string
	Size       *int64
	Path       *string
	MimeType   *string
	IsComplete bool
}

func (q *Queries) CreateFile(ctx context.Context, arg *CreateFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Name,
		arg.Size,
		arg.Path,
		arg.MimeType,
		arg.IsComplete,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Size,
		&i.Path,
		&i.MimeType,
		&i.IsComplete,
	)
	return &i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name, location_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, slug, name, location_id
`

type CreateProjectParams struct {
	Slug       string
	Name       string
	LocationID *int32
}

func (q *Queries) CreateProject(ctx context.Context, arg *CreateProjectParams) (*Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Slug, arg.Name, arg.LocationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.LocationID,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, email_verified)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, name, email, email_verified, keycloak_reference
`

type CreateUserParams struct {
	Name          string
	Email         string
	EmailVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.EmailVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.KeycloakReference,
	)
	return &i, err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO versions (name, description, project_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, name, description, project_id
`

type CreateVersionParams struct {
	Name        string
	Description *string
	ProjectID   int64
}

func (q *Queries) CreateVersion(ctx context.Context, arg *CreateVersionParams) (*Version, error) {
	row := q.db.QueryRow(ctx, createVersion, arg.Name, arg.Description, arg.ProjectID)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.ProjectID,
	)
	return &i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE
FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteVersion = `-- name: DeleteVersion :exec
DELETE
FROM versions
WHERE id = $1
`

func (q *Queries) DeleteVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVersion, id)
	return err
}

const detachFileFromVersion = `-- name: DetachFileFromVersion :exec
DELETE
FROM versions_files
WHERE version_id = $1
  AND file_id = $2
`

type DetachFileFromVersionParams struct {
	VersionID int64
	FileID    int64
}

func (q *Queries) DetachFileFromVersion(ctx context.Context, arg *DetachFileFromVersionParams) error {
	_, err := q.db.Exec(ctx, detachFileFromVersion, arg.VersionID, arg.FileID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id,
       created_at,
       updated_at,
       name,
       size,
       path,
       mime_type,
       is_complete
FROM files
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (*File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Size,
		&i.Path,
		&i.MimeType,
		&i.IsComplete,
	)
	return &i, err
}

const getProject = `-- name: GetProject :one

SELECT id,
       created_at,
       updated_at,
       slug,
       name,
       location_id
FROM projects
WHERE id = $1
LIMIT 1
`

// Projects
func (q *Queries) GetProject(ctx context.Context, id int64) (*Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.LocationID,
	)
	return &i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id,
       created_at,
       updated_at,
       name,
       email,
       email_verified,
       keycloak_reference
FROM users
WHERE id = $1
LIMIT 1
`

// Users
func (q *Queries) GetUserById(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.KeycloakReference,
	)
	return &i, err
}

const getUserByKeycloakReference = `-- name: GetUserByKeycloakReference :one
SELECT id,
       created_at,
       updated_at,
       name,
       email,
       email_verified,
       keycloak_reference
FROM users
WHERE keycloak_reference = $1
LIMIT 1
`

func (q *Queries) GetUserByKeycloakReference(ctx context.Context, keycloakReference *string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByKeycloakReference, keycloakReference)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.KeycloakReference,
	)
	return &i, err
}

const getVersion = `-- name: GetVersion :one
SELECT id,
       created_at,
       updated_at,
       name,
       description,
       project_id
FROM versions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVersion(ctx context.Context, id int64) (*Version, error) {
	row := q.db.QueryRow(ctx, getVersion, id)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.ProjectID,
	)
	return &i, err
}

const listFiles = `-- name: ListFiles :many
SELECT files.id,
       files.created_at,
       files.updated_at,
       files.name,
       files.size,
       files.path,
       files.mime_type,
       files.is_complete
FROM files
         LEFT JOIN versions_files ON files.id = versions_files.file_id
WHERE ($1::BIGINT IS NULL OR versions_files.version_id = $1)
ORDER BY files.created_at DESC
LIMIT $3::BIGINT OFFSET $2::BIGINT
`

type ListFilesParams struct {
	VersionId *int64
	Offset    int64
	Limit     int64
}

func (q *Queries) ListFiles(ctx context.Context, arg *ListFilesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.VersionId, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Size,
			&i.Path,
			&i.MimeType,
			&i.IsComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many

SELECT id,
       created_at,
       updated_at,
       name,
       address,
       lat,
       lon
FROM locations
ORDER BY created_at DESC
`

// Locations
func (q *Queries) ListLocations(ctx context.Context) ([]*Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id,
       created_at,
       updated_at,
       slug,
       name,
       location_id
FROM projects
ORDER BY created_at DESC
LIMIT $2::BIGINT OFFSET $1::BIGINT
`

type ListProjectsParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) ListProjects(ctx context.Context, arg *ListProjectsParams) ([]*Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.Name,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT id, created_at, updated_at, name, description, project_id
FROM versions
WHERE ($1::BIGINT IS NULL OR project_id = $1)
ORDER BY created_at DESC
LIMIT $3::BIGINT OFFSET $2::BIGINT
`

type ListVersionsParams struct {
	ProjectId *int64
	Offset    int64
	Limit     int64
}

func (q *Queries) ListVersions(ctx context.Context, arg *ListVersionsParams) ([]*Version, error) {
	rows, err := q.db.Query(ctx, listVersions, arg.ProjectId, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Version
	for rows.Next() {
		var i Version
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET updated_at  = current_timestamp,
    name        = $2,
    size        = $3,
    path        = $4,
    mime_type   = $5,
    is_complete = $6
WHERE id = $1
RETURNING id, created_at, updated_at, name, size, path, mime_type, is_complete
`

type UpdateFileParams struct {
	ID         int64
	Name       string
	Size       *int64
	Path       *string
	MimeType   *string
	IsComplete bool
}

func (q *Queries) UpdateFile(ctx context.Context, arg *UpdateFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, updateFile,
		arg.ID,
		arg.Name,
		arg.Size,
		arg.Path,
		arg.MimeType,
		arg.IsComplete,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Size,
		&i.Path,
		&i.MimeType,
		&i.IsComplete,
	)
	return &i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET updated_at  = CURRENT_TIMESTAMP,
    slug        = $2,
    name        = $3,
    location_id = $4
WHERE id = $1
RETURNING id, created_at, updated_at, slug, name, location_id
`

type UpdateProjectParams struct {
	ID         int64
	Slug       string
	Name       string
	LocationID *int32
}

func (q *Queries) UpdateProject(ctx context.Context, arg *UpdateProjectParams) (*Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.LocationID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.Name,
		&i.LocationID,
	)
	return &i, err
}

const updateVersion = `-- name: UpdateVersion :one
UPDATE versions
SET updated_at  = CURRENT_TIMESTAMP,
    name        = $2,
    description = $3
WHERE id = $1
RETURNING id, created_at, updated_at, name, description, project_id
`

type UpdateVersionParams struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) UpdateVersion(ctx context.Context, arg *UpdateVersionParams) (*Version, error) {
	row := q.db.QueryRow(ctx, updateVersion, arg.ID, arg.Name, arg.Description)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.ProjectID,
	)
	return &i, err
}
