// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// AttachFileToVersionRequest defines model for AttachFileToVersionRequest.
type AttachFileToVersionRequest struct {
	FileId int64 `json:"fileId"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateVersionRequest defines model for CreateVersionRequest.
type CreateVersionRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	ProjectId   int64   `json:"projectId"`
}

// DetachFileFromVersionRequest defines model for DetachFileFromVersionRequest.
type DetachFileFromVersionRequest struct {
	FileId int64 `json:"fileId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// ListProjectsResponse defines model for ListProjectsResponse.
type ListProjectsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Projects []ProjectResponse `json:"projects"`
}

// ListVersionsResponse defines model for ListVersionsResponse.
type ListVersionsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Versions []VersionResponse `json:"versions"`
}

// ProjectResponse defines model for ProjectResponse.
type ProjectResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// UpdateVersionRequest defines model for UpdateVersionRequest.
type UpdateVersionRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          int64     `json:"id"`
	Name        string    `json:"name"`
	ProjectId   int64     `json:"projectId"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// PathProjectId defines model for PathProjectId.
type PathProjectId = int64

// PathVersionId defines model for PathVersionId.
type PathVersionId = int64

// QueryLimit defines model for QueryLimit.
type QueryLimit = int64

// QueryOffset defines model for QueryOffset.
type QueryOffset = int64

// QueryProjectId defines model for QueryProjectId.
type QueryProjectId = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListVersionsParams defines parameters for ListVersions.
type ListVersionsParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// ProjectId Project ID
	ProjectId *QueryProjectId `form:"projectId,omitempty" json:"projectId,omitempty"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectByIdJSONRequestBody defines body for UpdateProjectById for application/json ContentType.
type UpdateProjectByIdJSONRequestBody = UpdateProjectRequest

// CreateVersionJSONRequestBody defines body for CreateVersion for application/json ContentType.
type CreateVersionJSONRequestBody = CreateVersionRequest

// UpdateVersionByIdJSONRequestBody defines body for UpdateVersionById for application/json ContentType.
type UpdateVersionByIdJSONRequestBody = UpdateVersionRequest

// AttachFileToVersionJSONRequestBody defines body for AttachFileToVersion for application/json ContentType.
type AttachFileToVersionJSONRequestBody = AttachFileToVersionRequest

// DetachFileFromVersionJSONRequestBody defines body for DetachFileFromVersion for application/json ContentType.
type DetachFileFromVersionJSONRequestBody = DetachFileFromVersionRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZXW/bNhf+KwTf3r2yJbdZ0emuaZYiWJtmXbeLBdnASMc2O0lkSCqrZ+i/DyT1adGx",
	"nNpOshXoRWNR5xw+z3M+SC1xxFLOMsiUxOEScyJICgqE+euCqPmFYJ8hUmex/oFmOMScqDn2cEZS0H/V",
	"zz0s4CanAmIcKpGDh2U0h5ToF6dMpEThENNMvTzCHlYLDvZPmIHAReEZb7+CkJRla73d1s+/1ttPOYjF",
	"O5pSpd+IQUaCckWZ9vmefKFpniI2RVRBKpFiSIDKRYY4CMTJDLBnw7vRZpr4EmOwHQt8ISlPAIeTIPCG",
	"R/ZhOpXgCM3+3olM/kn5mnCYteKMZ5toOiLoBlQ+Qmcna2JoC2QbigrNsOQsk2DEeEzij3CTgzSoRCxT",
	"kJn/Es4TGhEdj/9Z6qCWLUfPBExxiP/nN0L37VPp/yAEEx9LJ9Zld3PHJEaV08LDZ5kCkZHkZxC3IMzb",
	"h4ulco6sd2TdFx4+Z+qU5Vl8uFDOmULWpX5WvqatvlaKRPNTmsAnVqZyizMuGAehqOVzShOwgmpSZJgk",
	"m8S/rKxc1QvZtVabxuWNAKKg1OfaMKxKW0Hg9wtUvtS4l0rQbKatyiSfddenixGv13OiNE04xL9fktHf",
	"wej70R9X/3/Wt7SyD2O2zJn1m9mEaYemdoynVEiFyuqpq4eaA2qizvIkIdd6pS2lvV33USpDQZNx4IKJ",
	"tyvG1xBsPLftudA5gUp3p4KlD668bgL1/KcgpW4h4XKDKKqFLh/vqFSlTOV6V0nV4LZsQ17VOrbtGDVT",
	"xr3pUZvKTZ2hVcGprRIhyKKHStVj6+ZWe1yHUymIx4VTmYzDcaplfV+cao8unFZZ6EEUmQoUv+7uFT8P",
	"nr8cBZNRMPkUBKH5Nw6C4DfcAiEmCkaKmkTuVQq6fSZ6D1a1PZzzeA8wrFBH9bDUAN726m1sFb+Ytf+S",
	"vmc381T6nqt3uXa1msoHS7a9AbWjLN7bVPEYErccZdoc3D3YaOs0m7L+qeuERRdMqDFl6PXFGYpZlKeQ",
	"KVIaVVSZzXWXNS0AhzgYB+OJaWAcMsIpDvGLcTB+YXN5blToE07924nfbukz2+y0WI03zUVnGDEGmluE",
	"S3dTa5b4rZN44Q1bXZ6Oi6uVM+LzINjZKcg5YDkOQx9+1CgeWc8ug3WEfusIW3j4uyGvuI6c5tCVpykR",
	"C5O5WYxIkiDeEKDITEPfmox08jDpoK5zSipvVUCqYxYvdgal8yRWdHNH15WiR+dkZzH0psw+kzbM+GHp",
	"tEEggjL4q1WAHYwWXi9B/WVdTgpbNBJQ0Cf9xPxeQnK8MHcz2yVt92rQkYhH/aJ1ztCbkkoD8dFmvOq7",
	"jd0BbPeOSAUuul7Yyytn0jjL3VtQe8UuOKTq712/HorAt6CGssdzB3ud+XhnBO6+ajrn+EFV85t+7tKP",
	"xXWYhFo1tn1eXzsEVTcNhxyCBi4/UMVx3rc85rHptqGsEkBzUbJhbCo3utexaeXse+CxqXfp9BTGptua",
	"FgejjpT2l/V3xQFjUwnJvTtH843zSY5N1R3BatXsJM26sWmv2AWHVP0THZsGsXfH2LRrAvc1Nt2nan7T",
	"z6CxaYCENtRYn5jvxKMpTezdJ1HRvK84x9fkR6q5O757D1LegKr/ZHRisUAEaXaRYo1i7qeVGIZoxfkF",
	"+JGq5c6v1f85vVg0Kr1MBUs3Kka/b+xZUnOR4BDPleKh7ycsIsmcSRW+Cl4FuLgq/gkAAP//y1UGJeQm",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
