// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OpenIdConnectScopes = "OpenIdConnect.Scopes"
)

// AttachFileToVersionRequest defines model for AttachFileToVersionRequest.
type AttachFileToVersionRequest struct {
	FileId int64 `json:"fileId"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	Name string `json:"name"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Name          string              `json:"name"`
}

// CreateVersionRequest defines model for CreateVersionRequest.
type CreateVersionRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	ProjectId   int64   `json:"projectId"`
}

// DetachFileFromVersionRequest defines model for DetachFileFromVersionRequest.
type DetachFileFromVersionRequest struct {
	FileId int64 `json:"fileId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// FileResponse defines model for FileResponse.
type FileResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Id         int64     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	MimeType   *string   `json:"mimeType"`
	Name       string    `json:"name"`
	Size       *int64    `json:"size"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// ListFilesResponse defines model for ListFilesResponse.
type ListFilesResponse struct {
	Files  []FileResponse `json:"files"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

// ListProjectsResponse defines model for ListProjectsResponse.
type ListProjectsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Projects []ProjectResponse `json:"projects"`
}

// ListVersionsResponse defines model for ListVersionsResponse.
type ListVersionsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Versions []VersionResponse `json:"versions"`
}

// ProjectResponse defines model for ProjectResponse.
type ProjectResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TokenInfoResponse defines model for TokenInfoResponse.
type TokenInfoResponse struct {
	Subject string `json:"subject"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// UpdateVersionRequest defines model for UpdateVersionRequest.
type UpdateVersionRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt     time.Time           `json:"createdAt"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Id            int64               `json:"id"`
	Name          string              `json:"name"`
	UpdatedAt     time.Time           `json:"updatedAt"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          int64     `json:"id"`
	Name        string    `json:"name"`
	ProjectId   int64     `json:"projectId"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// PathFileId defines model for PathFileId.
type PathFileId = int64

// PathProjectId defines model for PathProjectId.
type PathProjectId = int64

// PathUserId defines model for PathUserId.
type PathUserId = int64

// PathVersionId defines model for PathVersionId.
type PathVersionId = int64

// QueryLimit defines model for QueryLimit.
type QueryLimit = int64

// QueryOffset defines model for QueryOffset.
type QueryOffset = int64

// QueryProjectId defines model for QueryProjectId.
type QueryProjectId = int64

// QueryVersionId defines model for QueryVersionId.
type QueryVersionId = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// VersionId Version ID
	VersionId *QueryVersionId `form:"versionId,omitempty" json:"versionId,omitempty"`
}

// UploadFileMultipartBody defines parameters for UploadFile.
type UploadFileMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListVersionsParams defines parameters for ListVersions.
type ListVersionsParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// ProjectId Project ID
	ProjectId *QueryProjectId `form:"projectId,omitempty" json:"projectId,omitempty"`
}

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = CreateFileRequest

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody UploadFileMultipartBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectByIdJSONRequestBody defines body for UpdateProjectById for application/json ContentType.
type UpdateProjectByIdJSONRequestBody = UpdateProjectRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateVersionJSONRequestBody defines body for CreateVersion for application/json ContentType.
type CreateVersionJSONRequestBody = CreateVersionRequest

// UpdateVersionByIdJSONRequestBody defines body for UpdateVersionById for application/json ContentType.
type UpdateVersionByIdJSONRequestBody = UpdateVersionRequest

// AttachFileToVersionJSONRequestBody defines body for AttachFileToVersion for application/json ContentType.
type AttachFileToVersionJSONRequestBody = AttachFileToVersionRequest

// DetachFileFromVersionJSONRequestBody defines body for DetachFileFromVersion for application/json ContentType.
type DetachFileFromVersionJSONRequestBody = DetachFileFromVersionRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3ZPbthH/Vzho3kqJPOeaSfhU21dnrk1sN/HloZ5rB0euTvCRAA2AZysa/u8dfPBL",
	"BEWeKsmSmxk/+EQSu9jfbz+wS65RzLKcUaBSoGiNcsxxBhK4/ustlstXJIXrRP1FKIpQjuUS+YjiDFCE",
	"Fuaijzh8LAiHBEWSF+AjES8hw+qpBeMZlihChMrvLpGP5CoH8yfcA0dl6Ws5bzn7ALEcFJXX1/ch7UYA",
	"HxRVmIv7kPMbcEEYHRT1WF//X6X9swC++olkRKonEhAxJ7kkTMn8GX8mWZF5bOERCZnwJPM4yIJTLwfu",
	"5fgekG/U+6iWafRL9YJtXeAzzvIUUHQRhn5fs8yIspczQu1fwzq/WSwEOJQ2v3d0Fg8kH1CUmVWcmjr1",
	"rDQLhzXrULKrnL3kXV8N6NOm6w5AdnjTFW0vDYtuc8qFmz9BjVLRUeSMCtCR4AVOfoGPBQgNVMyoBKr/",
	"i/M8JTFWugUfhFJw3RL6DYcFitCfgibKBOaqCP7GOeO/WCFGZHejL3DiVUJLH71kdJGS+IgK1BJLH11T",
	"CZzi9Ffgj8D1o8dTpBLuGemeEV/66DWTr1hBk+Op8ppJz4hU1+xjatXnUuJYZ4t3zFK0xZicsxy4JIZN",
	"izqnbGXlSPRo4uX7asXb+kZ2p9xP84YDlqAUG9THOE5LG5StZmrJufwsG/cQkhN635Otnx6WbEPFE4T/",
	"vPLsQ33ZPhJpcd9TNq/vz7FUZEER+vd7PPs9nP0w+8/tn78Z3YVe1h/bjMqbgzuBDJO0q9oHtqTzhMFf",
	"7U/zmGWoBbV5xLFLfeE34GRBwAbBBS5SiaIFTgX4jQyTLO0Cd4ylgKlaoW/Xv7Ml9a4YTEPUr5Xr6jJs",
	"nDHadzyprdgrwoX0bNxWGU8uwWsgpUWa4rveXhtj9bdaJYmLeeiybt7ObPvyQWu1Zm2Xpa6gChOvOMtO",
	"KlB0Y19PlwyEUIVStB5hT3WjS4YJQ0MiYk2j5LnsgvksfPbdLLyYhRfvwjDS/+ZhGP6r7UgJljCTJAMX",
	"3CR5cgXgIyJeMnW/7FJryN0yksE7/WtbdQmfZZCnmNDdeLw1DvtIkN9hoyh9dunY3YDk1m6LPDmA6TeY",
	"QVRJ1oDclupX7qO31DJnBwgXpX4iQipaiWFeKRPq/+hKeqwG6HC0rCVizvFK/Z1Wh4yRo0DfyKwu9bfW",
	"5iMuXJ1J6pLfbG/INjaVbjHP0TdUB8npoNRVxBAuY0aqJQ7Zycbi07KTzYnT7VRnlF3tVEt02WkThdOO",
	"4F+qsjyFaDpWzr5jD0Cv6YINYykKc/dowq9udMm50Tp9JWcAs5lzKXOnHtPMmebYHn3Qw9JotbaneDJ8",
	"ojqhimr6MW4zeRyNDAdzmT3hvLfj5AkX3m0Mtp9iVQCGuOBErn5VZYfhxpsc6HXyklFqkwZr/3DDUxSh",
	"pZS5iILgAVZxyvDDPGFxzricExZwwGkmAvvLLIHHYP4J0nT2QNknGqjVSDKLGV2Q+4Jjq2elWke47tsR",
	"umD97vEVi98agd7zt9dewuIiAyrr5YjU5u/e1pRFKELhPJxf6KIuB4pzgiL07Tycf2vyzlLbIsA5CR4v",
	"gvrgcQ+VSYzmiirNyUU/2gye3rtLvOaWoDXsKP1pd9sxw9TbmwZ8ebvRC38Whnvrt/YPb46e65t/KHNf",
	"GrGu1Wr1glafvvTRX6Y84upsa4oXWYb5Sgchmng4Tb2FBUvie1E1UwS6VRGACQfATevVjrdAyBcsWe3N",
	"fP3ebtl1fRUWyx5+F3tToHtWdowQTMz5svgZJTzsUfikMXRAWPpdpw3WplNWmhBStYG6+F7p35UNXqz0",
	"uOlpXtwaLzuc7LIfvF4z76VFTRv0ctw69YRkf+Y0u/awNqV3tzKTuL5POGPejyAPZK/waKTeOR59KcR+",
	"BDkG1yD/g4R9oinDyWAau7I32Dh3LExZLEHOhOSAsy62dYF0RyjWk+HN6uj8Ia2MbnF9EqJFXuHpTls3",
	"+f7gHMp5WZFKkmMuA4XWLMESd0Hsd3CnQdsfd7gq2K8oST6ZgZfhD+MPtGf/e6KsodUkwrbbw4Olc9XY",
	"Pmb1fOhauNesP+VyOG8AqLBsuuwjRXHT3DtcXbzRdTyy1/cmFudQHTetFQeiDgcN1nWjYEKlbE2yc/HX",
	"vJB2lvWyNVWvBus4zVDVfFDbhcdk/ZmWz5PQywtnPdWagewNwP1HTeesZlLU/IM/2wufBE8NAK0YWwj7",
	"Gvq2PHojgB80ibbfeDtyBu0Mpg5QN3+ZMriTbwsDX0UEA3mfBYEZSAzlhueFXAKVysqQ1Iw4kIeOoVK5",
	"51F9zY4jdCzdGES8v1XxshvN5RI83DbaE4AIJHsAOqvGC5MxqSfuhwSnP9b/qhDytO09Yqw4CtbafMlS",
	"bsNJQbNzTraf0Ry0oprqb2dWTmk4NxOhA8n2G1CDrYDq3a0THKQdqe52vsF2ys2DxwayCv3m1bOR5oHd",
	"6EHrno23fI5c+vRe4zuH5sFjDYsDUYdLB+v6U60JzQNrkp1j9daJ9uk3D6p3YDZDZsdphpLcQW0XHpP1",
	"Z5rtJqG3pXmwbwAP1TzYJWr+wZ9JzYMJFBqJsQHW3yjOqmFajmW87DPO8SXjiXJuyzeXk5g3IeqfDU+M",
	"Laoxv2QNY3bjSgJTuOL8nO1E2bL107v/O74Ya1R8WXCWjTJGH+PVegbUon6lMwqClMU4XTIho+/D70NU",
	"3pb/DQAA//8hzPutW0MAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
