// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OpenIdConnectScopes = "OpenIdConnect.Scopes"
)

// AttachFileToVersionRequest defines model for AttachFileToVersionRequest.
type AttachFileToVersionRequest struct {
	FileId int64 `json:"fileId"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	Name string `json:"name"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Name          string              `json:"name"`
}

// CreateVersionRequest defines model for CreateVersionRequest.
type CreateVersionRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	ProjectId   int64   `json:"projectId"`
}

// DetachFileFromVersionRequest defines model for DetachFileFromVersionRequest.
type DetachFileFromVersionRequest struct {
	FileId int64 `json:"fileId"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// FileResponse defines model for FileResponse.
type FileResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Id         int64     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	MimeType   *string   `json:"mimeType"`
	Name       string    `json:"name"`
	Size       *int64    `json:"size"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// ListFilesResponse defines model for ListFilesResponse.
type ListFilesResponse struct {
	Files  []FileResponse `json:"files"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

// ListProjectsResponse defines model for ListProjectsResponse.
type ListProjectsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Projects []ProjectResponse `json:"projects"`
}

// ListVersionsResponse defines model for ListVersionsResponse.
type ListVersionsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Versions []VersionResponse `json:"versions"`
}

// ProjectResponse defines model for ProjectResponse.
type ProjectResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TokenInfoResponse defines model for TokenInfoResponse.
type TokenInfoResponse struct {
	Subject string `json:"subject"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// UpdateVersionRequest defines model for UpdateVersionRequest.
type UpdateVersionRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt     time.Time           `json:"createdAt"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Id            int64               `json:"id"`
	Name          string              `json:"name"`
	UpdatedAt     time.Time           `json:"updatedAt"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          int64     `json:"id"`
	Name        string    `json:"name"`
	ProjectId   int64     `json:"projectId"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// PathFileId defines model for PathFileId.
type PathFileId = int64

// PathProjectId defines model for PathProjectId.
type PathProjectId = int64

// PathUserId defines model for PathUserId.
type PathUserId = int64

// PathVersionId defines model for PathVersionId.
type PathVersionId = int64

// QueryLimit defines model for QueryLimit.
type QueryLimit = int64

// QueryOffset defines model for QueryOffset.
type QueryOffset = int64

// QueryProjectId defines model for QueryProjectId.
type QueryProjectId = int64

// QueryVersionId defines model for QueryVersionId.
type QueryVersionId = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// VersionId Version ID
	VersionId *QueryVersionId `form:"versionId,omitempty" json:"versionId,omitempty"`
}

// UploadFileMultipartBody defines parameters for UploadFile.
type UploadFileMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListVersionsParams defines parameters for ListVersions.
type ListVersionsParams struct {
	// Limit Maximum of items to return per page
	Limit *QueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *QueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// ProjectId Project ID
	ProjectId *QueryProjectId `form:"projectId,omitempty" json:"projectId,omitempty"`
}

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = CreateFileRequest

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody UploadFileMultipartBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectByIdJSONRequestBody defines body for UpdateProjectById for application/json ContentType.
type UpdateProjectByIdJSONRequestBody = UpdateProjectRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateVersionJSONRequestBody defines body for CreateVersion for application/json ContentType.
type CreateVersionJSONRequestBody = CreateVersionRequest

// UpdateVersionByIdJSONRequestBody defines body for UpdateVersionById for application/json ContentType.
type UpdateVersionByIdJSONRequestBody = UpdateVersionRequest

// AttachFileToVersionJSONRequestBody defines body for AttachFileToVersion for application/json ContentType.
type AttachFileToVersionJSONRequestBody = AttachFileToVersionRequest

// DetachFileFromVersionJSONRequestBody defines body for DetachFileFromVersion for application/json ContentType.
type DetachFileFromVersionJSONRequestBody = DetachFileFromVersionRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3XPbuBH/VzjovZUS6Zx7c6enJnFz4/YuSe/ie2jG7cDkykJMAggAOtZp+L93APBT",
	"BEVKlWQpvRk/WPzaxf5++4FdcoUilnJGgSqJZivEscApKBDm13usFm9IAtex/kUomiGO1QL5iOIU0AzN",
	"7UkfCficEQExmimRgY9ktIAU67vmTKRYoRkiVH13iXyklhzsT7gHgfLcN3LeC/YJItUrilfn9yHtRoLo",
	"FZXZk/uQ8xsISRjtFfVYnf9fpf0zA7H8iaRE6TtikJEgXBGmZf6Mn0iapR6be0RBKj3FPAEqE9TjIDyO",
	"7wH5Vr3P+jG1fol5YFMXeMIpTwDNLsLQH6/Zu/lcgkM1e7ylmXwgvEcdZp/i1GcbbVpkaytUnPKur3p0",
	"aBJxB4hajGiLLk71i26yxYXIGAvkmmiSMyrB+PgrHP8CnzOQBpyIUQXU/Is5T0iEtW7BJ6kVXDWEfiNg",
	"jmboT0EdPwJ7VgZ/E4KJXwohVmR7oa9w7JVCcx+9ZnSekOiIClQScx9dUwWC4uRXEI8gzK3HU6QU7lnp",
	"nhWf++gtU29YRuPjqfKWKc+K1OeK2/RTXyqFI5MHPrCCog3GcME4CEUsm+ZVttjIypRQHZCM0zocpY6E",
	"H8sn3lYXsjvtfoY3ArACrVivPtZxGtqgdDnRj5yqJ1W7h1SC0PuObHN3v+QiVGwh/OelV9zUle0jmWT3",
	"HWV5dT3HSpMFzdC/P+LJ7+Hkh8l/bv/8zeAqzGP9ocXojNi7EkgxSdqqfWILOo0Z/LU4NI1YihpQ21sc",
	"qzQnfgNB5gTaTLFpr7jhjrEEMNV3dO34d7ag3hWDcQj6lTJt2f3GGKJ5y3Oair0hQiqviNM6q6kFeDWE",
	"NEsSfNdZa22c7lLLpHAxDV3W5M1Mtl0mcFqqfp7LOldQhoI3gqUnFQza8a2jSwpS6jJnthpgTHmhS4YN",
	"NX0iIkOd+KVqA/gifPHdJLyYhBcfwnBm/qZhGP6r6SwxVjBRJAUXxGR7bH1E5Gumr1cwysVSksIHc7Sp",
	"uoInFfAEE7obdzfGWh9J8juslZQvLh2r65HcWG3G4wOYfo0ZRJddNchNqX7pPmZJDXO2gHBR6icilaaV",
	"7OeVNqH5x1TIQ3m+xdG8koiFwEv9Oym3CFsW8n5ZfO9QczetWO4oqlLeLq/PNkW63GCeoy+oCpLjQakq",
	"hT5choxUSeyzUxGLT8tORR4cb6cqo+xqp0qiy07rKJx2BH+u6vEUoulQyfqBPQC9pnPWj6XM7NWDCb+8",
	"0CXnxuj0ldT5djHnUtqO3YrZfcuxPfp5N0R7iif9u6gTqqjGb93Wk8fRyHAwl9kTzgfbQp4QTZoYbN7F",
	"6gAMUSaIWv6qyw7LjXcc6HX8mlFaJA3WPHAjEjRDC6W4nAXBAyyjhOGHacwizoSaEhYIwEkqg+LIJIbH",
	"YPoFkmTyQNkXGuinkXgSMTon95nAhZ6lai3hpjdH6Jx1O8RXLHpvBXov3197MYuyFKiqHkeUMX/7sros",
	"QjMUTsPphSnqOFDMCZqhb6fh9FubdxbGFgHmJHi8CKqNxz2UJrGaa6rUOxdzaz02+ugu8epLgsaoIvfH",
	"XV2MD8ZeXjfZ89u1fveLMNxbT7W7eXP0Vd/9Q5v70op1Pa1SL2j04nMf/WXMLa7utaF4lqZYLE0QorGH",
	"k8SbF2ApfC/LZopEtzoCMOkAuG6vFsMpkOoVi5d7M1+3f5u3XV+HxbyD38XeFGjvlR1jAhtznhc/q4SH",
	"PQpfDIYOCHO/7bTBynbKchtCyjZQG98rc1zb4NXSjJS28+LGcNjhZJfd4PWWea8L1IxBL4etU01B9mdO",
	"u2oPG1N6d0s7bev6hDPm/QjqQPYKj0bqnePRcyH2I6ghuHr5H8TsC00YjnvT2FVxQRHnjoUpixSoiVQC",
	"cNrGtiqQ7gjFZvq7Xh2dP6Sl0Qtct0I04yWe7rR1w/cHZ1/OS7NEEY6FCjRakxgr3Aax28EdB2133OGq",
	"YL+iJLk1Ay/DH4ZvaM7390RZS6tRhG22h3tL57Kxfczq+dC1cKdZf8rlMK8BKLGsu+wDRXHd3DtcXbzW",
	"dTyy13cmFudQHdetFQeiDgcNVlWjYESlXJhk5+KvfunsLOvlwlSdGqzlNH1V80FtFx6T9WdaPo9Cj2fO",
	"eqoxA9kbgPuPms5Zzaio+Qd/Nhc+MR4bABoxNpPFS+Sb8uiNBHHQJNp8q+3IGbQ1mDpA3fw8ZXAr32YW",
	"vpIIFvIuCwI7kOjLDS8ztQCqtJUhrhhxIA8dQqV0z6P6WjGOMLF0bRDx8VbHy3Y0VwvwcNNoWwARKPYA",
	"dFKOF0ZjUk3cDwlOd6z/VSHkGdt7xFpxEKyV/Q4l34SThmbnnFx8BHPQimqsv51ZOWXgXE+EDiSbb0D1",
	"tgLKd7dOcJB2pLrb+QbbKTcPHmvISvTrV88GmgfFQg9a96y95XPk0qfzGt85NA8eK1gciDpcOlhVn2ON",
	"aB4UJtk5Vm+caJ9+86B8B2Y9ZLacpi/JHdR24TFZf6bZbhR6G5oH+wbwUM2DXaLmH/wZ1TwYQaGBGBtg",
	"8x3ipBymcayiRZdxjq8VT5RzG76rHMW8EVH/bHhibVGO+RWrGbMbV2IYwxXn52wnypaNn9793/HFWqPk",
	"y1ywdJAxZhuvn2dBzapXOmdBkLAIJwsm1ez78PsQ5bf5fwMAAP//sHdYaBlDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
