// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// ListProjectsResponse defines model for ListProjectsResponse.
type ListProjectsResponse struct {
	Limit    int64             `json:"limit"`
	Offset   int64             `json:"offset"`
	Projects []ProjectResponse `json:"projects"`
}

// ProjectResponse defines model for ProjectResponse.
type ProjectResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Limit defines model for Limit.
type Limit = int64

// Offset defines model for Offset.
type Offset = int64

// ProjectId defines model for ProjectId.
type ProjectId = int64

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Maximum of items to return per page
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectByIdJSONRequestBody defines body for UpdateProjectById for application/json ContentType.
type UpdateProjectByIdJSONRequestBody = UpdateProjectRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWb2/bthP+KsT9+u4nW3SaFZ3eNc1aBGvToNveLMgGVjrb7CSRIU9ZPUPffSAp60+k",
	"zN7gJsAwwC8s6XjP8bm7524LqSq0KrEkC8kWtDCiQELjn97JQpL7k6FNjdQkVQkJvBdfZFEVTC2ZJCws",
	"I8UMUmVKptEwLVYIEUhneluh2UAEpSgQEsi9wwhsusZCOM/4RRQ6R0gWnEewVKYQBAnIkl6cQgS00Rge",
	"cYUG6jqCD8ulxYmowvtBUPY3qR+IRAUvk6EcGMiVUZ8xpYvMHfYYWtC6g9Dt9wgM3lbSYAYJmQr7qPuR",
	"anfcalVa9Fk5E9lHvK3QehJSVRKW/q/QOpepcHzEn60jZdsDemZwCQn8L+4yHoevNv7OGGU+NiABckju",
	"mcjYDrSO4KIkNKXIf0Bzh8affrxYduAsoLMAX0dwqeiNqsrs8UK5VMQCpPvWHHNeXxsUhE2F9LKljdJo",
	"SIZMhkLpVR6837DmUFcJlowsV+6CNq9WQ/tiM9OtvRbkmIEEfrkWsz/47NvZrzf/fzb2VPcL8jq4bcr2",
	"pjVWn7zbOoIhDaNbFGita/lkuwdnZziF8U5aam5uH4bKd4K0t2uiXYcfZtyQ6EG8fOwrjTa1u+JovQpj",
	"xGZ0953ytbrTIk6xcd/7iIjU11f2ioblcMJPXsz4YsYXP3Ke+N+cc/4z9BQtE4QzkgVOVZjMhqIcHULe",
	"U5VxBJXOvgIN91InnYB3hPdRo72985O3/VcIgbOW5VKNR++5Sq+UoblU7NXVBctUWhVYkpdcByrJxzg0",
	"gwju0Njggc/5fOG7VmMptIQEns/5/Hm4zNqTFAst47tF3O/VVehwx6VHc8N4oCXeQbfTXE93dWcSh52n",
	"jvYaNntIfXNvPJ9wfrQBNKmKE3Pow/eOu9OAPOWwjTDubQ91BN8ccmRq2vt5VxWFMBtI4I0sMybynOmO",
	"dhIrR3hP6JzOKjuRsMG0bLYltHSmss3RqJycyPWwA9xuVo/SuThaDKOhMc5kCDN72nSGIJhgJf7OOlmZ",
	"yGgdjdoy3raLbx2kIkfCcdLP/fuGkrONX5P/Xqt2C/hEE56OZepSsddNGj29p/u5alfK45Eb7s3Ejlj2",
	"acMuzh9qmEmBe4v01Xjjj1nt/1i3nip5b5EOzZyuJjI3WAeOkrzjK+XkynKQUv5XO39VO4HXw8rHn/Se",
	"QlFUJocE1kQ6ieNcpSJfK0vJS/6SQ31T/xkAAP//Ho8zI8cRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
